#!/usr/bin/env bash
# link.sh — Symlink manager (backup, link, idempotent)
set -euo pipefail

DOT_DIR="${DOT_DIR:-$(cd "$(dirname "$0")/.." && pwd)}"
DRY_RUN="${DOT_DRY_RUN:-false}"
DOT_REMOTE="${DOT_REMOTE:-false}"
BACKUP_DIR="$HOME/.dotfiles-backup"
LINK_ERRORS=0

# Create parent directories
ensure_dirs() {
    local dirs=(
        "$HOME/.config"
        "$HOME/.config/ghostty"
        "$HOME/.config/zed"
        "$HOME/.claude"
        "$BACKUP_DIR"
    )
    for d in "${dirs[@]}"; do
        if [ "$DRY_RUN" = true ]; then
            [ ! -d "$d" ] && echo "  [DRY-RUN] Would create directory: $d"
        else
            mkdir -p "$d"
        fi
    done
}

# Backup and link a single file
# Usage: do_link <source> <target>
do_link() {
    local src="$1"
    local target="$2"

    if [ ! -e "$src" ] && [ ! -L "$src" ]; then
        echo "  [WARN] Source does not exist: $src"
        LINK_ERRORS=$((LINK_ERRORS + 1))
        return
    fi

    # Already correctly linked?
    if [ -L "$target" ]; then
        local current_target
        current_target="$(readlink "$target")"
        if [ "$current_target" = "$src" ]; then
            echo "  [OK] Already linked: $target"
            return
        else
            # Points somewhere else
            if [ "$DRY_RUN" = true ]; then
                echo "  [DRY-RUN] Would replace symlink: $target (currently -> $current_target)"
                return
            fi
            echo "  [REPLACE] $target (was -> $current_target)"
            ln -sfn "$src" "$target"
            return
        fi
    fi

    # Target exists as a regular file — backup first
    if [ -e "$target" ]; then
        local backup_name
        backup_name="$(basename "$target").$(date +%Y%m%d_%H%M%S)"
        if [ "$DRY_RUN" = true ]; then
            echo "  [DRY-RUN] Would backup $target -> $BACKUP_DIR/$backup_name"
            echo "  [DRY-RUN] Would link $target -> $src"
            return
        fi
        echo "  [BACKUP] $target -> $BACKUP_DIR/$backup_name"
        mv "$target" "$BACKUP_DIR/$backup_name"
    fi

    if [ "$DRY_RUN" = true ]; then
        echo "  [DRY-RUN] Would link: $target -> $src"
        return
    fi

    ln -sfn "$src" "$target"
    echo "  [LINK] $target -> $src"
}

# --- Git config (generated, not symlinked) ---
# Local installs: [user] section with name/email baked in.
# Remote installs: no [user] section — identity via env vars from dot-ssh.
setup_gitconfig() {
    local template="$DOT_DIR/git/gitconfig.template"
    local target="$HOME/.gitconfig"

    if [ ! -f "$template" ]; then
        echo "  [WARN] Git config template not found: $template"
        return
    fi

    # Read existing identity BEFORE backup (so we don't lose it)
    local git_name=""
    local git_email=""
    if [ "$DOT_REMOTE" != true ]; then
        # Try current gitconfig file
        if [ -f "$target" ] || [ -L "$target" ]; then
            git_name="$(git config --file "$target" user.name 2>/dev/null || echo "")"
            git_email="$(git config --file "$target" user.email 2>/dev/null || echo "")"
        fi
        # Fallback to global git config
        [ -z "$git_name" ] && git_name="$(git config user.name 2>/dev/null || echo "")"
        [ -z "$git_email" ] && git_email="$(git config user.email 2>/dev/null || echo "")"
    fi

    if [ "$DRY_RUN" = true ]; then
        echo "  [DRY-RUN] Would generate ~/.gitconfig"
        return
    fi

    # Backup existing if it's a real file (not our generated one)
    if [ -e "$target" ] && [ ! -L "$target" ]; then
        if ! grep -q "# Generated by dot/install.sh" "$target" 2>/dev/null; then
            local backup_name="gitconfig.$(date +%Y%m%d_%H%M%S)"
            echo "  [BACKUP] $target -> $BACKUP_DIR/$backup_name"
            mv "$target" "$BACKUP_DIR/$backup_name"
        fi
    elif [ -L "$target" ]; then
        rm -f "$target"
    fi

    # Generate from template
    local content
    content="$(cat "$template")"

    # Remote: strip SSH URL rewrite and skip [user] (identity via dot-ssh env vars)
    if [ "$DOT_REMOTE" = true ]; then
        content="$(echo "$content" | sed '/\[url "ssh:\/\/git@github.com\/"\]/,/insteadOf = https:\/\/github.com\//d')"
    else
        # Local: prompt if interactive and still missing
        if [ -z "$git_name" ] && [ "${DOT_IS_INTERACTIVE:-false}" = true ]; then
            printf "  Git user.name: "
            read -r git_name
        fi
        if [ -z "$git_email" ] && [ "${DOT_IS_INTERACTIVE:-false}" = true ]; then
            printf "  Git user.email: "
            read -r git_email
        fi

        # Prepend [user] section if we have identity
        if [ -n "$git_name" ] && [ -n "$git_email" ]; then
            local user_section
            user_section="$(printf '[user]\n    name = %s\n    email = %s\n' "$git_name" "$git_email")"
            content="${user_section}
${content}"
            echo "  [GIT] Identity: $git_name <$git_email>"
        else
            echo "  [WARN] Git user.name/email not set — run: git config --global user.name 'Your Name'"
        fi
    fi

    echo "$content" > "$target"
    echo "  [GEN] $target"
}

# --- Main ---
link_all() {
    echo "=== Linking Configuration Files ==="
    ensure_dirs

    # Shell configs — always
    do_link "$DOT_DIR/shell/bashrc" "$HOME/.bashrc"
    do_link "$DOT_DIR/shell/bash_profile" "$HOME/.bash_profile"

    # Zsh — only if available
    if [ "${DOT_HAS_ZSH:-false}" = true ] || command -v zsh >/dev/null 2>&1; then
        do_link "$DOT_DIR/shell/zshrc" "$HOME/.zshrc"
        do_link "$DOT_DIR/shell/zprofile" "$HOME/.zprofile"
    fi

    # Git
    setup_gitconfig
    do_link "$DOT_DIR/git/gitignore_global" "$HOME/.gitignore_global"

    # tmux
    do_link "$DOT_DIR/tmux/tmux.conf" "$HOME/.tmux.conf"

    # macOS-only
    if [ "${DOT_OS:-}" = "macos" ] && [ "$DOT_REMOTE" != true ]; then
        do_link "$DOT_DIR/ghostty/config" "$HOME/.config/ghostty/config"
        do_link "$DOT_DIR/ghostty/themes" "$HOME/.config/ghostty/themes"
        do_link "$DOT_DIR/zed/settings.json" "$HOME/.config/zed/settings.json"
    fi

    # Claude — if installed
    if command -v claude >/dev/null 2>&1 || [ "${DOT_HAS_CLAUDE:-false}" = true ]; then
        do_link "$DOT_DIR/claude/settings.json" "$HOME/.claude/settings.json"
    fi

    echo ""

    # Stale symlink check
    echo "  Checking for stale symlinks..."
    local stale_count=0
    while IFS= read -r link; do
        if [ -L "$link" ]; then
            local link_target
            link_target="$(readlink "$link")"
            case "$link_target" in
                "$DOT_DIR"/*)
                    if [ ! -e "$link" ]; then
                        echo "  [STALE] $link -> $link_target"
                        stale_count=$((stale_count + 1))
                    fi
                    ;;
            esac
        fi
    done < <(find "$HOME" -maxdepth 3 -type l 2>/dev/null || true)

    if [ "$stale_count" -eq 0 ]; then
        echo "  [OK] No stale symlinks found"
    fi

    if [ "$LINK_ERRORS" -gt 0 ]; then
        echo "  [WARN] $LINK_ERRORS link error(s) encountered"
        return 1
    fi
}

link_all
